[pytest]
env =
<<<<<<< HEAD
    NEOMODEL_CYPHER_CONNECTION_URL=bolt://neo4j:password123@localhost:7687
=======
    NEOMODEL_CYPHER_CONNECTION_URL=bolt://ignored:ignored@localhost:7788
>>>>>>> 9c5f532 (proper config for db path)
